name: Run MATLAB Tests on GitHub-Hosted Runner
on: [push]
jobs:
  setup-fortran:
    name: "setup-fortran: ${{ matrix.compiler }} on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-13]
        compiler: [gcc, intel-classic]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - uses: fortran-lang/setup-fortran@v1
        with:
          compiler: ${{ matrix.compiler }}
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v3
      - name: Setup MEX
        uses: matlab-actions/run-command@v3
        with:
          command: mex -setup Fortran

  homebrew-gcc:
    name: "homebrew gcc on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Install gfortran via Homebrew
        run: brew install gcc
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v3
      - name: Setup MEX
        uses: matlab-actions/run-command@v3
        with:
          command: mex -setup Fortran

  homebrew-flang:
    name: "homebrew flang on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Install flang via LLVM
        run: brew install llvm flang
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v3
      - name: Setup MEX
        uses: matlab-actions/run-command@v3
        with:
          command: mex -setup Fortran

  homebrew-simply-fortran:
    name: "simply-fortran on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Install Simply Fortran
        run: brew install --cask simply-fortran
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v3
      - name: Setup MEX
        uses: matlab-actions/run-command@v3
        with:
          command: mex -setup Fortran
